added output check bash command

diff --git a/.github/workflows/laravel-testings.yml b/.github/workflows/laravel-testings.yml
--- a/.github/workflows/laravel-testings.yml
+++ b/.github/workflows/laravel-testings.yml
@@ -77,12 +77,21 @@ jobs:
           ./vendor/bin/pint --test ${{ steps.changed-files.outputs.all_changed_files }}
 
       - name: Run PHPUnit Tests
+        id: tests
         run: |
-          php artisan test
-          if [ $? -eq 0 ]; then
-            echo "Tests passed successfully."
+          OUTPUT=$(php artisan test)
+          echo "$OUTPUT"
+          echo "::set-output name=result::$OUTPUT"
+
+      - name: Check test results
+        run: |
+          if echo "${{ steps.tests.outputs.result }}" | grep -q 'failed'; then
+            echo "Tests failed."
+            exit 1
+          elif echo "${{ steps.tests.outputs.result }}" | grep -q 'passed'; then
+            echo "Tests passed."
             exit 0
           else
-            echo "Tests failed."
+            echo "Unexpected test results."
             exit 1
           fi
