added additional condition to verify test pass/fail

diff --git a/.github/workflows/laravel-testings.yml b/.github/workflows/laravel-testings.yml
--- a/.github/workflows/laravel-testings.yml
+++ b/.github/workflows/laravel-testings.yml
@@ -78,4 +78,11 @@ jobs:
 
       - name: Run PHPUnit Tests
         run: |
-          ./vendor/bin/phpunit || true
+          php artisan test
+          if [ $? -eq 0 ]; then
+            echo "Tests passed successfully."
+            exit 0
+          else
+            echo "Tests failed."
+            exit 1
+          fi
